feat: extension Save 컴포넌트 작업
DDD-Community/KDKD-Client pull request #21
Opened 2023-08-05 10:19 UTC by dkkim0122

* shadcn/ui의 input 커스터마이징
  * helper text 추가
  * focus될 때 border color 변경(emotion css prop 사용, tsconfig에 jsxImportSource 속성 추가)
* 이미지 및 svg 추가
  * vite-plugin-svgr은 yarn build 시 오류가 발생되어 svg파일을 react component로 만들어서 사용하고 있음. 혹시 더 좋은 방법이 있다면은 공유해주시면 감사하겠습니다!
* tag 생성하는 input 컴포넌트 제작
  * 텍스트 입력 후 Enter 누르면 태그 생성, Backspace 누르면 태그 삭제
  * 태그가 많아져 너비를 초과하면 줄바꿈

[TagInput]

https://github.com/DDD-Community/KDKD-Client/assets/93521799/4b7828eb-4d18-4471-8354-47c767baead8

2023-08-06 02:38 UTC, nimuseel commented on src/components/Extension/Save.tsx
> +        <section style={styles.urlInfoSection}>
[제안]

`urlInfoSection` 스타일을 갖는 컴포넌트가 여럿 있는데, `UrlInfoSection` 컴포넌트를 만드는 것은 어떨까요?

2023-08-06 02:39 UTC, nimuseel commented on src/components/common/TagInput.tsx
> +    }
[제안]

이 부분은 `setShowPlaceholder(inputValue.length === 0 && tags.length === 0)` 로 축약시킬 수 있을 것 같은데, 변경하는 것은 어떨까요?

2023-08-06 02:46 UTC, nimuseel requested changes
제안 코멘트들 남겼습니다!

2023-08-06 02:46 UTC, nimuseel commented on src/components/common/TagInput.tsx
> +    }
[제안]

이 부분은 setShowPlaceholder(inputValue.length === 0 && tags.length === 0) 로 축약시킬 수 있을 것 같은데, 변경하는 것은 어떨까요?

2023-08-06 02:46 UTC, nimuseel commented on src/components/Extension/Save.tsx
> +        </section>
[제안]

urlInfoSection 스타일을 갖는 컴포넌트가 여럿 있는데, UrlInfoSection 컴포넌트를 만드는 것은 어떨까요?

2023-08-06 02:46 UTC, nimuseel commented on src/components/common/TagInput.tsx
> +    setInputWidth((inputValue.length + 1) * CHARACTER_WIDTH);
[제안]

input의 너비값을 상태로 관리하는 것은 괜히 불필요한 리렌더를 발생시키는 요인이 될 수 있을 것 같은데요, input 스타일에 `(inputValue.length + 1) * CHARACTER_WIDTH` 를 직접 inline 시키는 것은 어떨까요?

굳이 character width를 상수로 관리하는 것이 아니라 `(inputValue.length + 1) * 10.5`가 될 수도 있을 것 같고요 :)

2023-08-06 02:46 UTC, nimuseel commented on src/components/Extension/Save.tsx
> +  const [pageOGImage, setPageOGImage] = useState('');
[제안]

이 코드는 현재 사용되는 곳이 없어 제거되는 것이 좋을 것 같습니다 :)

2023-08-06 02:46 UTC, nimuseel commented on src/components/Extension/Save.tsx
> +  }, [urlTitle]);
[제안]

에러 상태를 state로서 핸들링하는 것보단, form을 사용하는 것이 더 나은 방법일 것 같은데, form을 활용하도록 변경하는 것은 어떨까요?

react-hook-form을 사용해볼 수 있을 것 같습니다~

2023-08-06 03:52 UTC, dkkim0122 commented on src/components/common/TagInput.tsx
> +    }
오 좋습니다 👍

2023-08-06 03:53 UTC, dkkim0122 commented on src/components/Extension/Save.tsx
> +        </section>
컴포넌트 만들어서 재사용할 수 있겠네요 그렇게 바꾸겠습니다 👍

2023-08-06 03:56 UTC, dkkim0122 commented on src/components/Extension/Save.tsx
> +  }, [urlTitle]);
안 그래도 shadcn에 form이 있더라구요. 참고해서 바꿔보겠습니다:)

2023-08-06 03:57 UTC, dkkim0122 commented on src/components/Extension/Save.tsx
> +  const [pageOGImage, setPageOGImage] = useState('');
앞으로 사용 상태들이라 일단은 적어놓긴 했는데 삭제하는게 좋을까요?

2023-08-06 13:04 UTC, dkkim0122 commented on src/components/common/TagInput.tsx
> +    setInputWidth((inputValue.length + 1) * CHARACTER_WIDTH);
잘 몰라서 여쭤봅니다! 지금과 같은 방식을 사용했을 때 왜 불필요한 리렌더링이 일어나는지 조금만 설명 부탁드려도 될까요? 사실 말씀하신 거처럼 굳이 새 상태를 만들지 않고 inputValue만으로도 width를 계산해 줄 수 있는데, 이렇게 불필요한 상태를 굳이 만들 필요가 없기 때문이다, 이렇게 이해하면 될라나요?

2023-08-10 10:17 UTC, dkkim0122 commented on src/components/common/TagInput.tsx
> +    setInputWidth((inputValue.length + 1) * CHARACTER_WIDTH);
일단 직접 inputValue를 사용하게끔 개선했습니다! `CHARACTER_WIDTH`를 굳이 매직넘버로 사용하려 했던 이유는 나중에 다시 코드를 보았을 때 10.5가 무엇인지 잘 알아볼 수 있도록 하기 위해서라, 웬만하면 남겨 놓으려 하는데 어떻게 생각하시나요?? 이런 상수들은 이름 붙여서 관리하려 하긴 합니다!

2023-08-12 11:13 UTC, nimuseel commented on src/components/common/TagInput.tsx
> +    setInputWidth((inputValue.length + 1) * CHARACTER_WIDTH);
@dkkim0122 

> 굳이 새 상태를 만들지 않고 inputValue만으로도 width를 계산해 줄 수 있는데, 이렇게 불필요한 상태를 굳이 만들 필요가 없기 때문이다

맞습니다! 상태가 업데이트 되면 해당 컴포넌트는 리렌더링 되니까요 ㅎㅎ

2023-08-12 11:14 UTC, nimuseel commented on src/components/common/TagInput.tsx
> +    setInputWidth((inputValue.length + 1) * CHARACTER_WIDTH);
상수로 남겨 놓아도 괜찮긴 하겠네요~

2023-08-12 11:18 UTC, nimuseel approved these changes
코멘트 하나 더 남기긴 했는데, 사소하다고 판단되어 Approve 누릅니다!

2023-08-12 11:18 UTC, nimuseel commented on src/components/Extension/UrlInfoSection.tsx
> +function UrlInfoSection({ children, label }: Props) {
리액트에 `PropsWithChildren` 을 사용하면 children props를 명시해 주지 않아도 돼요!

`PropsWithChildren<Props>` 형태로 사용하면 됩니다 ㅎㅎ

2023-08-13 03:00 UTC, dkkim0122 commented on src/components/Extension/UrlInfoSection.tsx
> +function UrlInfoSection({ children, label }: Props) {
오 꿀팁이군요! 나중에 변경할때 적용하겠습니다!!! 감사합니다:)

2023-08-13 03:00 UTC, merged