최근 검색 UI 구현
DDD-Community/KDKD-Client pull request #28
Opened 2023-08-23 14:05 UTC by nimuseel

- 추후 검색 API 연동 필요
- 태그 컴포넌트 제작 필요

<img width="1797" alt="스크린샷 2023-08-23 오후 11 04 30" src="https://github.com/DDD-Community/KDKD-Client/assets/48236404/c8b0d93f-1165-4fd5-8f15-46ef6c818225">

2023-08-24 02:06 UTC, dkkim0122 requested changes
고생하셨습니다! 일단 제안사항이랑 질문사항 작성하기는 했는데, 제안사항은 보시고 괜찮겠다 싶으면은 적용해보고 안 해도 되겠다 싶으면 괜찮을 거 같습니다:)

2023-08-24 02:06 UTC, dkkim0122 commented on index.html
> +    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=1,viewport-fit=cover">
혹시 이 속성 추가하신 히스토리를 들을 수 있을까요??? 화면 표시 관련해서 사용하신 걸까요?

2023-08-24 02:06 UTC, dkkim0122 commented on src/components/Home/GNB/RecentlySearch/styles.ts
> +`;
사진과 같이 뷰포트의 너비에 따라 search 결과 컴포넌트의 위치가 input이랑 맞지 않는 것 같아 보입니다😭 사실 이거는 GNB Input 위치가 뷰포트 너비 상관없이 가만히 있어서 생기는 문제인 거 같습니다
<img width="1720" alt="image" src="https://github.com/DDD-Community/KDKD-Client/assets/93521799/bf8a60ea-e87b-4887-a99b-9359033088ed">

2023-08-24 02:06 UTC, dkkim0122 commented on src/components/Home/GNB/RecentlySearch/index.tsx
> +      'rgba(0, 0, 0, 0.5)';
아이디어 제안 드립니다:)
지금은 GNB 제외한 나머지 웹을 나타내는 컨테이너 요소에 content라는 id를 넣어 dimmed된 백그라운드를 제공하신 걸로 이해가 됩니다! 직접 document 객체에 접근해서 스타일을 변경시키는 작업이기도 하고, content id 요소가 있는 Home 컴포넌트가 아닌 다른 컴포넌트에서 변경이 이루어지다 보니 헷갈릴 수 있겠다는 생각이 듭니다.
RecentlySearchWrapper 컴포넌트의 상위 컴포넌트로 화면 전체를 덮을 수 있는 div 요소를 만들어 이 컴포넌트로 dimmed 처리를 하고(width: 100vh에 height는 헤더 제외한 높이, z-index가 있어야 할지도 모르겠습니다) 그 안에다가 search 결과 컴포넌트를 넣으면 어떨지 의견 드려봅니다.
사실 저도 트라이해보지는 않아서 어떻게 될지는 모르겠으나... 이런 방향은 어떨까요?

2023-08-24 02:06 UTC, dkkim0122 commented on src/pages/Home.tsx
> +      </div>
만약 이렇게 쭉 가신다면은 LNB도 넣어서 한번 보면 좋을 것 같습니다! 현재 main에 머지된 상태입니다:)

2023-08-26 06:45 UTC, nimuseel commented on index.html
> +    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=1,viewport-fit=cover">
반응형 미지원 관련 내용 구두 설명 완료!

2023-08-26 07:40 UTC, dkkim0122 approved these changes

2023-08-26 07:41 UTC, merged