feat: 로그인 관련 API 연동
DDD-Community/KDKD-Client pull request #33
Opened 2023-09-02 10:44 UTC by dkkim0122

* 로그인 토큰은 쿠키에 저장
  * 익스텐션과 웹이 사용하는 쿠키가 다르므로 useAuth에서 함수를 구분하여 사용하도록 함
* API 호출 시 Authrization 헤더 필드가 필요한 경우 쿠키에 접근하여 토큰 유무 확인 후 API  요청할 수 있도록 함 => extension과 web에서 사용하는 SWR Fetcher를 구분함
* extention) 로그인 여부를 redux toolkit에 저장하여 Main에서 로그인 여부 확인할 수 있도록 함

### 주의사항
* 백엔드에서 포트 번호 3000에 CORS 에러 나지 않도록 되어 있다 하여 포트 번호를 3000으로 수정하였습니다

2023-09-02 11:17 UTC, nimuseel requested changes
코멘트 남겼습니다~

2023-09-02 11:17 UTC, nimuseel commented on src/api/extension.ts
> +          Authorization: `Bearer ${accessTokenCookie.value}`,
accessToken 불러오는 걸 더 상위로 빼는 게 좋을 것 같습니다!

매번 fetcherWithToken을 사용해야할 뿐더러, 굳이 분리할 필요성이 있을까 의문점이 있어서요!

2023-09-02 11:17 UTC, nimuseel commented on src/api/extension.ts
> +export const fetcherWithParams = async ([url, params]: string[]) => {
제가 사용하면서 느꼈던 건데... 굳이 url과 params를 나눠서 받을 필요가 있나 싶었어요

fetcher 하나만 사용하는 건 어떨까요?

2023-09-03 01:29 UTC, dkkim0122 commented on src/api/extension.ts
> +          Authorization: `Bearer ${accessTokenCookie.value}`,
그렇담 fetcherWithToken과 fetcher를 분리하지 않고 fetcher에 토큰 검증 로직도 포함하도록 하겠습니다! 보니까 웬만한 API들은 모두 Authorization 필드가 필요하네요.

2023-09-03 01:30 UTC, dkkim0122 commented on src/api/extension.ts
> +export const fetcherWithParams = async ([url, params]: string[]) => {
그렇게 바꿔보겠습니다:)

2023-09-03 02:15 UTC, nimuseel commented on src/components/Home/SearchResult/index.tsx
> +    ([url, params]: string[]) => fetcher(url, params),
SWR은 key 기반으로 타입 추론이 돼서 `fetcher` 만 써도 될 거에요!

2023-09-03 02:15 UTC, nimuseel approved these changes
LGTM!

2023-09-03 02:18 UTC, dkkim0122 commented on src/components/Home/SearchResult/index.tsx
> +    ([url, params]: string[]) => fetcher(url, params),
이상하게 vscode에서 이 친구만 타입 any라고 에러가 뜨더라구요... 시간날때 잡아버ㅣ보겠습니다

2023-09-03 12:01 UTC, merged